# Default keyboard bindings.

[bindings]
"Digit0" = "SelectSlot(0)"
"Digit1" = "SelectSlot(1)"
"Digit2" = "SelectSlot(2)"
"Digit3" = "SelectSlot(3)"
"Digit4" = "SelectSlot(4)"
"Digit5" = "SelectSlot(5)"
"Digit6" = "SelectSlot(6)"
"Digit7" = "SelectSlot(7)"
"Digit8" = "SelectSlot(8)"
"Digit9" = "SelectSlot(9)"
"BracketLeft" = "SetLoopIn"
"BracketRight" = "SetLoopOut"
"Backslash" = "ClearLoop"
"Space" = "TogglePlayPause"
"Tab" = "ToggleNowNext"
"KeyB" = "EnterMode(Browser)"
"KeyS" = "EnterMode(Sampler)"
"KeyG" = "EnterMode(Settings)"
"Comma" = "PrevBank"
"Period" = "NextBank"
"ArrowUp" = "NavUp"
"ArrowDown" = "NavDown"
"ArrowLeft" = "NavLeft"
"ArrowRight" = "NavRight"
"Enter" = "Enter"
"Escape" = "Back"
"Backspace" = "Back"
"ShiftLeft" = "ToggleFunction"
"KeyH" = "EnterMode(Shaders)"
"KeyK" = "EnterMode(ShdrBnk)"
"F1" = "TriggerShaderSlot(0)"
"F2" = "TriggerShaderSlot(1)"
"F3" = "TriggerShaderSlot(2)"
"F4" = "TriggerShaderSlot(3)"
"F5" = "TriggerShaderSlot(4)"
"F6" = "TriggerShaderSlot(5)"
"F7" = "TriggerShaderSlot(6)"
"F8" = "TriggerShaderSlot(7)"
"F9" = "TriggerShaderSlot(8)"
"F10" = "TriggerShaderSlot(9)"
