project: r_e_c_u_Rs
statuses:
    - idea
    - planned
    - active
    - done
    - cancelled
blocked: true
types:
    - feature
    - bug
    - idea
    - task
    - epic
priorities:
    - critical
    - high
    - medium
    - low
defaults:
    status: idea
    priority: medium
